"""empty message

Revision ID: 4526050316aa
Revises: ec5f2a43102f
Create Date: 2022-12-10 15:26:03.378696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4526050316aa'
down_revision = 'ec5f2a43102f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('tsin_id', sa.String(), nullable=False),
    sa.Column('Role', sa.String(), nullable=False),
    sa.Column('Chapter', sa.String(), nullable=False),
    sa.Column('Squad', sa.String(), nullable=False),
    sa.Column('demand_type', sa.String(), nullable=True),
    sa.Column('Tribe', sa.String(), nullable=True),
    sa.Column('snow_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tsin_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
