"""empty message

Revision ID: 68d654a68c57
Revises: 
Create Date: 2022-12-09 16:22:43.535199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d654a68c57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tsin_id', sa.String(), nullable=False),
    sa.Column('candidate_name', sa.String(), nullable=False),
    sa.Column('candidate_email', sa.String(), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=False),
    sa.Column('pan', sa.String(), nullable=True),
    sa.Column('request_raised_date', sa.String(), nullable=True),
    sa.Column('tsin_opened_date', sa.String(), nullable=True),
    sa.Column('resume_screened_date', sa.String(), nullable=True),
    sa.Column('l1_interview_date', sa.String(), nullable=True),
    sa.Column('l1_interviewer', sa.String(), nullable=True),
    sa.Column('l1_interview_result', sa.String(), nullable=True),
    sa.Column('l1_interview_remarks', sa.String(), nullable=True),
    sa.Column('l2_interview_date', sa.String(), nullable=True),
    sa.Column('l2_interviewer', sa.String(), nullable=True),
    sa.Column('l2_interview_result', sa.String(), nullable=True),
    sa.Column('l2_interview_remarks', sa.String(), nullable=True),
    sa.Column('l3_interview_date', sa.String(), nullable=True),
    sa.Column('l3_interviewer', sa.String(), nullable=True),
    sa.Column('l3_interview_result', sa.String(), nullable=True),
    sa.Column('l3_interview_remarks', sa.String(), nullable=True),
    sa.Column('offer_rollout_date', sa.String(), nullable=True),
    sa.Column('joining_date', sa.String(), nullable=True),
    sa.Column('buddy_assignment_date', sa.String(), nullable=True),
    sa.Column('buddy_name', sa.String(), nullable=True),
    sa.Column('candidate_dropout_date', sa.String(), nullable=True),
    sa.Column('candidate_dropout_reason', sa.String(), nullable=True),
    sa.Column('resume', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('current_location', sa.String(), nullable=True),
    sa.Column('current_company', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('candidate_joined_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('tsin_id', sa.Integer(), nullable=False),
    sa.Column('Role', sa.String(), nullable=False),
    sa.Column('Chapter', sa.String(), nullable=False),
    sa.Column('Squad', sa.String(), nullable=False),
    sa.Column('demand_type', sa.String(), nullable=True),
    sa.Column('Tribe', sa.String(), nullable=True),
    sa.Column('snow_id', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('tsin_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('candidates')
    # ### end Alembic commands ###
