"""empty message

Revision ID: ec5f2a43102f
Revises: 45e83160617a
Create Date: 2022-12-10 15:25:02.353639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5f2a43102f'
down_revision = '45e83160617a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('tsin_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Chapter', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Squad', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('demand_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Tribe', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('snow_id', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('tsin_id', name='roles_pkey')
    )
    # ### end Alembic commands ###
